"""make route courier nullable and add pending status"""

revision = '5235152486c5'
down_revision = '0008_add_product_selling_price'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    # Add 'pending' to route_status enum
    op.execute(sa.text("ALTER TYPE route_status ADD VALUE IF NOT EXISTS 'pending'"))

    op.alter_column('routes', 'courier_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'courier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_orders_route_id_stop_sequence'), 'orders', ['route_id', 'stop_sequence'], unique=False)
    # ### end Alembic commands ###
