"""add_is_superuser"""

revision = '8134853912b4'
down_revision = '0009_phase_2_indexes'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_log_order_id_changed_at'), table_name='order_status_log')
    op.drop_index(op.f('ix_orders_courier_id_status_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_route_id_stop_sequence'), table_name='orders')
    op.drop_index(op.f('ix_orders_status_created_at'), table_name='orders')
    op.drop_index(op.f('ix_products_stock_quantity_title'), table_name='products')
    op.drop_index(op.f('ix_routes_courier_id_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_status_created_at'), table_name='routes')
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.create_index(op.f('ix_routes_status_created_at'), 'routes', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_routes_courier_id_status'), 'routes', ['courier_id', 'status'], unique=False)
    op.create_index(op.f('ix_products_stock_quantity_title'), 'products', ['stock_quantity', 'title'], unique=False)
    op.create_index(op.f('ix_orders_status_created_at'), 'orders', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_orders_route_id_stop_sequence'), 'orders', ['route_id', 'stop_sequence'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_customer_phone'), 'orders', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_orders_courier_id_status_created_at'), 'orders', ['courier_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_order_status_log_order_id_changed_at'), 'order_status_log', ['order_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###
