"""add_admin_id_to_all_models"""

revision = 'dfeebc348e01'
down_revision = '8134853912b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['admin_id'], ['id'])
    op.add_column('products', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['admin_id'], ['id'])
    op.add_column('routes', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'routes', 'users', ['admin_id'], ['id'])
    op.add_column('users', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'admin_id')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'admin_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'admin_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'admin_id')
    # ### end Alembic commands ###
